### ISSUE TITLE
One Of developer reason

### ISSUE THREAD

**Issue by rootflood** [rootflood/MonsajemFramworks_For_Bridgedotnet#1]
i dont know why they don't fix this:
https://github.com/bridgedotnet/Bridge/issues/3940
thanks a lot from @geoffreymcgill and others salty guys in bridge project

however we dont using bridge.net anymore from 4/2019

**Comment by geoffreymcgill** [comment]
> however we dont using bridge.net anymore from 4/2019

good

**Comment by rootflood** [comment]
no, is grate
you cant understand

**Comment by rootflood** [comment]
@geoffreymcgill 
https://webassembly.org/docs/faq/
this is software revolution, not about me or you

i offered bridge.net to our group but they tell it's not safe(bugs, do you remeber?)
i hard trying to fix and patch that
do you know what my manager say? kis mis byby
thats all.
